version: "3.1"

services:
  # Gateway
  gateway:
    image: ghcr.io/hawks-atlanta/gateway-java:latest
    container_name: gateway
    restart: on-failure
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      METADATA_BASEURL: http://metadata:8080
      AUTHENTICATION_BASEURL: http://authentication:8080
      WORKER_HOST: worker
      WORKER_PORT: 8080
    depends_on:
      - worker
      - metadata
      - authentication

  # Microservices
  worker:
    image: ghcr.io/hawks-atlanta/worker-java:latest
    container_name: worker
    restart: on-failure
    ports:
      - "127.0.0.1:8081:8080"
  metadata:
    image: ghcr.io/hawks-atlanta/metadata-scala:latest
    container_name: metadata
    restart: on-failure
    ports:
      - "127.0.0.1:8082:8080"
    environment:
      DATABASE_HOST: "metadata-db"
      DATABASE_PORT: "5432"
      DATABASE_NAME: "database"
      DATABASE_USER: "username"
      DATABASE_PASSWORD: "password"
    depends_on:
      - metadata-db
  authentication:
    image: ghcr.io/hawks-atlanta/authentication-go:latest
    container_name: authentication
    restart: on-failure
    ports:
      - "127.0.0.1:8083:8080"
    environment:
      DATABASE_ENGINE: postgres
      DATABASE_DSN: "host=authentication-db user=username password=password dbname=database port=5432 sslmode=disable"
    depends_on:
      - authentication-db

  # Databases
  authentication-db:
    image: postgres:alpine3.18
    container_name: authentication-db
    restart: on-failure
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
  metadata-db:
    image: postgres:alpine3.18
    container_name: metadata-db
    restart: on-failure
    ports:
      - "127.0.0.1:5434:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
  postgres-admin:
    image: dpage/pgadmin4
    container_name: postgres-admin
    ports:
      - "127.0.0.1:5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - authentication-db
      - metadata-db

  # Proxy-net
  # Local/Docker http://gateway:8080/service
  # Remote       http://capyfile1.bucaramanga.upb.edu.co/service
  proxy-net:
    container_name: proxy-net
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - SERVICE_URL=http://gateway:8080/service # NO ADD ?WSDL! | connect to Localhost with using name "gateway" container
      - ASPNETCORE_ENVIRONMENT=Development      # Development | Production
    ports:
      - 8084:80
    depends_on:
      - gateway
      - worker
      - metadata
      - authentication
      - authentication-db
      - metadata-db
      - postgres-admin
