//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.gateway/", ConfigurationName="ServiceReference.Service")]
    public interface Service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/auth_loginRequest", ReplyAction="http://soap.gateway/Service/auth_loginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.auth_loginResponse> auth_loginAsync(ServiceReference.auth_loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/auth_refreshRequest", ReplyAction="http://soap.gateway/Service/auth_refreshResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.auth_refreshResponse> auth_refreshAsync(ServiceReference.auth_refreshRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/account_registerRequest", ReplyAction="http://soap.gateway/Service/account_registerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.account_registerResponse> account_registerAsync(ServiceReference.account_registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/account_passwordRequest", ReplyAction="http://soap.gateway/Service/account_passwordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.account_passwordResponse> account_passwordAsync(ServiceReference.account_passwordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/file_uploadRequest", ReplyAction="http://soap.gateway/Service/file_uploadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.file_uploadResponse> file_uploadAsync(ServiceReference.file_uploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/file_new_dirRequest", ReplyAction="http://soap.gateway/Service/file_new_dirResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.file_new_dirResponse> file_new_dirAsync(ServiceReference.file_new_dirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/file_getRequest", ReplyAction="http://soap.gateway/Service/file_getResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.file_getResponse> file_getAsync(ServiceReference.file_getRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/file_checkRequest", ReplyAction="http://soap.gateway/Service/file_checkResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.file_checkResponse> file_checkAsync(ServiceReference.file_checkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/file_deleteRequest", ReplyAction="http://soap.gateway/Service/file_deleteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.file_deleteResponse> file_deleteAsync(ServiceReference.file_deleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/file_listRequest", ReplyAction="http://soap.gateway/Service/file_listResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.file_listResponse> file_listAsync(ServiceReference.file_listRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/file_downloadRequest", ReplyAction="http://soap.gateway/Service/file_downloadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.file_downloadResponse> file_downloadAsync(ServiceReference.file_downloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/file_moveRequest", ReplyAction="http://soap.gateway/Service/file_moveResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.file_moveResponse> file_moveAsync(ServiceReference.file_moveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/file_renameRequest", ReplyAction="http://soap.gateway/Service/file_renameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.file_renameResponse> file_renameAsync(ServiceReference.file_renameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/share_fileRequest", ReplyAction="http://soap.gateway/Service/share_fileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.share_fileResponse> share_fileAsync(ServiceReference.share_fileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/unshare_fileRequest", ReplyAction="http://soap.gateway/Service/unshare_fileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.unshare_fileResponse> unshare_fileAsync(ServiceReference.unshare_fileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/share_listRequest", ReplyAction="http://soap.gateway/Service/share_listResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.share_listResponse> share_listAsync(ServiceReference.share_listRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.gateway/Service/share_list_with_whoRequest", ReplyAction="http://soap.gateway/Service/share_list_with_whoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.share_list_with_whoResponse> share_list_with_whoAsync(ServiceReference.share_list_with_whoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class credentials
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class reqShareRemove
    {
        
        private string fileUUIDField;
        
        private string otherUsernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileUUID
        {
            get
            {
                return this.fileUUIDField;
            }
            set
            {
                this.fileUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string otherUsername
        {
            get
            {
                return this.otherUsernameField;
            }
            set
            {
                this.otherUsernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(reqShareFile))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(reqFileMove))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(reqAccPassword))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(reqFileNewDir))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(reqFileUpload))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(reqFile))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(reqFileRename))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(reqFileDelete))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(reqFileList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class authorization
    {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class reqShareFile : authorization
    {
        
        private string fileUUIDField;
        
        private string otherUsernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileUUID
        {
            get
            {
                return this.fileUUIDField;
            }
            set
            {
                this.fileUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string otherUsername
        {
            get
            {
                return this.otherUsernameField;
            }
            set
            {
                this.otherUsernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class reqFileMove : authorization
    {
        
        private string fileUUIDField;
        
        private string targetDirectoryUUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileUUID
        {
            get
            {
                return this.fileUUIDField;
            }
            set
            {
                this.fileUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string targetDirectoryUUID
        {
            get
            {
                return this.targetDirectoryUUIDField;
            }
            set
            {
                this.targetDirectoryUUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class reqAccPassword : authorization
    {
        
        private string oldpasswordField;
        
        private string newpasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string oldpassword
        {
            get
            {
                return this.oldpasswordField;
            }
            set
            {
                this.oldpasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string newpassword
        {
            get
            {
                return this.newpasswordField;
            }
            set
            {
                this.newpasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class reqFileNewDir : authorization
    {
        
        private string directoryNameField;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string directoryName
        {
            get
            {
                return this.directoryNameField;
            }
            set
            {
                this.directoryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class reqFileUpload : authorization
    {
        
        private string fileNameField;
        
        private byte[] fileContentField;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] fileContent
        {
            get
            {
                return this.fileContentField;
            }
            set
            {
                this.fileContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class reqFile : authorization
    {
        
        private string fileUUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileUUID
        {
            get
            {
                return this.fileUUIDField;
            }
            set
            {
                this.fileUUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class reqFileRename : authorization
    {
        
        private string fileUUIDField;
        
        private string newNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileUUID
        {
            get
            {
                return this.fileUUIDField;
            }
            set
            {
                this.fileUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string newName
        {
            get
            {
                return this.newNameField;
            }
            set
            {
                this.newNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class reqFileDelete : authorization
    {
        
        private string[] fileUUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileUUID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] fileUUID
        {
            get
            {
                return this.fileUUIDField;
            }
            set
            {
                this.fileUUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class reqFileList : authorization
    {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sharedFile))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class file
    {
        
        private string uuidField;
        
        private string nameField;
        
        private string extensionField;
        
        private bool isFileField;
        
        private int sizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool isFile
        {
            get
            {
                return this.isFileField;
            }
            set
            {
                this.isFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class sharedFile : file
    {
        
        private string ownerUsernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ownerUsername
        {
            get
            {
                return this.ownerUsernameField;
            }
            set
            {
                this.ownerUsernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resShareListWithWho))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resFileGet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resShareList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resFileCheck))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resFileNew))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resFileDownload))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resSession))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resFileList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class resStatus
    {
        
        private int codeField;
        
        private bool errorField;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string msg
        {
            get
            {
                return this.msgField;
            }
            set
            {
                this.msgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class resShareListWithWho : resStatus
    {
        
        private string[] usernamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("usernames", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] usernames
        {
            get
            {
                return this.usernamesField;
            }
            set
            {
                this.usernamesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class resFileGet : resStatus
    {
        
        private file fileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public file file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class resShareList : resStatus
    {
        
        private sharedFile[] sharedFilesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sharedFiles", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public sharedFile[] sharedFiles
        {
            get
            {
                return this.sharedFilesField;
            }
            set
            {
                this.sharedFilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class resFileCheck : resStatus
    {
        
        private bool readyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool ready
        {
            get
            {
                return this.readyField;
            }
            set
            {
                this.readyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class resFileNew : resStatus
    {
        
        private string fileUUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileUUID
        {
            get
            {
                return this.fileUUIDField;
            }
            set
            {
                this.fileUUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class resFileDownload : resStatus
    {
        
        private string fileUUIDField;
        
        private string fileNameField;
        
        private byte[] fileContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileUUID
        {
            get
            {
                return this.fileUUIDField;
            }
            set
            {
                this.fileUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] fileContent
        {
            get
            {
                return this.fileContentField;
            }
            set
            {
                this.fileContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class resSession : resStatus
    {
        
        private authorization authField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public authorization auth
        {
            get
            {
                return this.authField;
            }
            set
            {
                this.authField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.gateway/")]
    public partial class resFileList : resStatus
    {
        
        private file[] filesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public file[] files
        {
            get
            {
                return this.filesField;
            }
            set
            {
                this.filesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="auth_login", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class auth_loginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.credentials arg0;
        
        public auth_loginRequest()
        {
        }
        
        public auth_loginRequest(ServiceReference.credentials arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="auth_loginResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class auth_loginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resSession @return;
        
        public auth_loginResponse()
        {
        }
        
        public auth_loginResponse(ServiceReference.resSession @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="auth_refresh", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class auth_refreshRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.authorization arg0;
        
        public auth_refreshRequest()
        {
        }
        
        public auth_refreshRequest(ServiceReference.authorization arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="auth_refreshResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class auth_refreshResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resSession @return;
        
        public auth_refreshResponse()
        {
        }
        
        public auth_refreshResponse(ServiceReference.resSession @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="account_register", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class account_registerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.credentials arg0;
        
        public account_registerRequest()
        {
        }
        
        public account_registerRequest(ServiceReference.credentials arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="account_registerResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class account_registerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resSession @return;
        
        public account_registerResponse()
        {
        }
        
        public account_registerResponse(ServiceReference.resSession @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="account_password", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class account_passwordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.reqAccPassword arg0;
        
        public account_passwordRequest()
        {
        }
        
        public account_passwordRequest(ServiceReference.reqAccPassword arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="account_passwordResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class account_passwordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resStatus @return;
        
        public account_passwordResponse()
        {
        }
        
        public account_passwordResponse(ServiceReference.resStatus @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_upload", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_uploadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.reqFileUpload arg0;
        
        public file_uploadRequest()
        {
        }
        
        public file_uploadRequest(ServiceReference.reqFileUpload arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_uploadResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_uploadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resFileNew @return;
        
        public file_uploadResponse()
        {
        }
        
        public file_uploadResponse(ServiceReference.resFileNew @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_new_dir", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_new_dirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.reqFileNewDir arg0;
        
        public file_new_dirRequest()
        {
        }
        
        public file_new_dirRequest(ServiceReference.reqFileNewDir arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_new_dirResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_new_dirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resFileNew @return;
        
        public file_new_dirResponse()
        {
        }
        
        public file_new_dirResponse(ServiceReference.resFileNew @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_get", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_getRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.reqFile arg0;
        
        public file_getRequest()
        {
        }
        
        public file_getRequest(ServiceReference.reqFile arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_getResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_getResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resFileGet @return;
        
        public file_getResponse()
        {
        }
        
        public file_getResponse(ServiceReference.resFileGet @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_check", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_checkRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.reqFile arg0;
        
        public file_checkRequest()
        {
        }
        
        public file_checkRequest(ServiceReference.reqFile arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_checkResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_checkResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resFileCheck @return;
        
        public file_checkResponse()
        {
        }
        
        public file_checkResponse(ServiceReference.resFileCheck @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_delete", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_deleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.reqFileDelete arg0;
        
        public file_deleteRequest()
        {
        }
        
        public file_deleteRequest(ServiceReference.reqFileDelete arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_deleteResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_deleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resStatus @return;
        
        public file_deleteResponse()
        {
        }
        
        public file_deleteResponse(ServiceReference.resStatus @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_list", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_listRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.reqFileList arg0;
        
        public file_listRequest()
        {
        }
        
        public file_listRequest(ServiceReference.reqFileList arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_listResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_listResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resFileList @return;
        
        public file_listResponse()
        {
        }
        
        public file_listResponse(ServiceReference.resFileList @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_download", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_downloadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.reqFile arg0;
        
        public file_downloadRequest()
        {
        }
        
        public file_downloadRequest(ServiceReference.reqFile arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_downloadResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_downloadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resFileDownload @return;
        
        public file_downloadResponse()
        {
        }
        
        public file_downloadResponse(ServiceReference.resFileDownload @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_move", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_moveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.reqFileMove arg0;
        
        public file_moveRequest()
        {
        }
        
        public file_moveRequest(ServiceReference.reqFileMove arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_moveResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_moveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resStatus @return;
        
        public file_moveResponse()
        {
        }
        
        public file_moveResponse(ServiceReference.resStatus @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_rename", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_renameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.reqFileRename arg0;
        
        public file_renameRequest()
        {
        }
        
        public file_renameRequest(ServiceReference.reqFileRename arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="file_renameResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class file_renameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resStatus @return;
        
        public file_renameResponse()
        {
        }
        
        public file_renameResponse(ServiceReference.resStatus @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="share_file", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class share_fileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.reqShareFile arg0;
        
        public share_fileRequest()
        {
        }
        
        public share_fileRequest(ServiceReference.reqShareFile arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="share_fileResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class share_fileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resStatus @return;
        
        public share_fileResponse()
        {
        }
        
        public share_fileResponse(ServiceReference.resStatus @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unshare_file", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class unshare_fileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.reqShareRemove arg0;
        
        public unshare_fileRequest()
        {
        }
        
        public unshare_fileRequest(ServiceReference.reqShareRemove arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unshare_fileResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class unshare_fileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resStatus @return;
        
        public unshare_fileResponse()
        {
        }
        
        public unshare_fileResponse(ServiceReference.resStatus @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="share_list", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class share_listRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.authorization arg0;
        
        public share_listRequest()
        {
        }
        
        public share_listRequest(ServiceReference.authorization arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="share_listResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class share_listResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resShareList @return;
        
        public share_listResponse()
        {
        }
        
        public share_listResponse(ServiceReference.resShareList @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="share_list_with_who", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class share_list_with_whoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.reqFile arg0;
        
        public share_list_with_whoRequest()
        {
        }
        
        public share_list_with_whoRequest(ServiceReference.reqFile arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="share_list_with_whoResponse", WrapperNamespace="http://soap.gateway/", IsWrapped=true)]
    public partial class share_list_with_whoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.gateway/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.resShareListWithWho @return;
        
        public share_list_with_whoResponse()
        {
        }
        
        public share_list_with_whoResponse(ServiceReference.resShareListWithWho @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ServiceChannel : ServiceReference.Service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ServiceReference.Service>, ServiceReference.Service
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServiceImpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.auth_loginResponse> ServiceReference.Service.auth_loginAsync(ServiceReference.auth_loginRequest request)
        {
            return base.Channel.auth_loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.auth_loginResponse> auth_loginAsync(ServiceReference.credentials arg0)
        {
            ServiceReference.auth_loginRequest inValue = new ServiceReference.auth_loginRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).auth_loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.auth_refreshResponse> ServiceReference.Service.auth_refreshAsync(ServiceReference.auth_refreshRequest request)
        {
            return base.Channel.auth_refreshAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.auth_refreshResponse> auth_refreshAsync(ServiceReference.authorization arg0)
        {
            ServiceReference.auth_refreshRequest inValue = new ServiceReference.auth_refreshRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).auth_refreshAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.account_registerResponse> ServiceReference.Service.account_registerAsync(ServiceReference.account_registerRequest request)
        {
            return base.Channel.account_registerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.account_registerResponse> account_registerAsync(ServiceReference.credentials arg0)
        {
            ServiceReference.account_registerRequest inValue = new ServiceReference.account_registerRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).account_registerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.account_passwordResponse> ServiceReference.Service.account_passwordAsync(ServiceReference.account_passwordRequest request)
        {
            return base.Channel.account_passwordAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.account_passwordResponse> account_passwordAsync(ServiceReference.reqAccPassword arg0)
        {
            ServiceReference.account_passwordRequest inValue = new ServiceReference.account_passwordRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).account_passwordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.file_uploadResponse> ServiceReference.Service.file_uploadAsync(ServiceReference.file_uploadRequest request)
        {
            return base.Channel.file_uploadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.file_uploadResponse> file_uploadAsync(ServiceReference.reqFileUpload arg0)
        {
            ServiceReference.file_uploadRequest inValue = new ServiceReference.file_uploadRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).file_uploadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.file_new_dirResponse> ServiceReference.Service.file_new_dirAsync(ServiceReference.file_new_dirRequest request)
        {
            return base.Channel.file_new_dirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.file_new_dirResponse> file_new_dirAsync(ServiceReference.reqFileNewDir arg0)
        {
            ServiceReference.file_new_dirRequest inValue = new ServiceReference.file_new_dirRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).file_new_dirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.file_getResponse> ServiceReference.Service.file_getAsync(ServiceReference.file_getRequest request)
        {
            return base.Channel.file_getAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.file_getResponse> file_getAsync(ServiceReference.reqFile arg0)
        {
            ServiceReference.file_getRequest inValue = new ServiceReference.file_getRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).file_getAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.file_checkResponse> ServiceReference.Service.file_checkAsync(ServiceReference.file_checkRequest request)
        {
            return base.Channel.file_checkAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.file_checkResponse> file_checkAsync(ServiceReference.reqFile arg0)
        {
            ServiceReference.file_checkRequest inValue = new ServiceReference.file_checkRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).file_checkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.file_deleteResponse> ServiceReference.Service.file_deleteAsync(ServiceReference.file_deleteRequest request)
        {
            return base.Channel.file_deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.file_deleteResponse> file_deleteAsync(ServiceReference.reqFileDelete arg0)
        {
            ServiceReference.file_deleteRequest inValue = new ServiceReference.file_deleteRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).file_deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.file_listResponse> ServiceReference.Service.file_listAsync(ServiceReference.file_listRequest request)
        {
            return base.Channel.file_listAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.file_listResponse> file_listAsync(ServiceReference.reqFileList arg0)
        {
            ServiceReference.file_listRequest inValue = new ServiceReference.file_listRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).file_listAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.file_downloadResponse> ServiceReference.Service.file_downloadAsync(ServiceReference.file_downloadRequest request)
        {
            return base.Channel.file_downloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.file_downloadResponse> file_downloadAsync(ServiceReference.reqFile arg0)
        {
            ServiceReference.file_downloadRequest inValue = new ServiceReference.file_downloadRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).file_downloadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.file_moveResponse> ServiceReference.Service.file_moveAsync(ServiceReference.file_moveRequest request)
        {
            return base.Channel.file_moveAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.file_moveResponse> file_moveAsync(ServiceReference.reqFileMove arg0)
        {
            ServiceReference.file_moveRequest inValue = new ServiceReference.file_moveRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).file_moveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.file_renameResponse> ServiceReference.Service.file_renameAsync(ServiceReference.file_renameRequest request)
        {
            return base.Channel.file_renameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.file_renameResponse> file_renameAsync(ServiceReference.reqFileRename arg0)
        {
            ServiceReference.file_renameRequest inValue = new ServiceReference.file_renameRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).file_renameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.share_fileResponse> ServiceReference.Service.share_fileAsync(ServiceReference.share_fileRequest request)
        {
            return base.Channel.share_fileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.share_fileResponse> share_fileAsync(ServiceReference.reqShareFile arg0)
        {
            ServiceReference.share_fileRequest inValue = new ServiceReference.share_fileRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).share_fileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.unshare_fileResponse> ServiceReference.Service.unshare_fileAsync(ServiceReference.unshare_fileRequest request)
        {
            return base.Channel.unshare_fileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.unshare_fileResponse> unshare_fileAsync(ServiceReference.reqShareRemove arg0)
        {
            ServiceReference.unshare_fileRequest inValue = new ServiceReference.unshare_fileRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).unshare_fileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.share_listResponse> ServiceReference.Service.share_listAsync(ServiceReference.share_listRequest request)
        {
            return base.Channel.share_listAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.share_listResponse> share_listAsync(ServiceReference.authorization arg0)
        {
            ServiceReference.share_listRequest inValue = new ServiceReference.share_listRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).share_listAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.share_list_with_whoResponse> ServiceReference.Service.share_list_with_whoAsync(ServiceReference.share_list_with_whoRequest request)
        {
            return base.Channel.share_list_with_whoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.share_list_with_whoResponse> share_list_with_whoAsync(ServiceReference.reqFile arg0)
        {
            ServiceReference.share_list_with_whoRequest inValue = new ServiceReference.share_list_with_whoRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.Service)(this)).share_list_with_whoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceImpPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceImpPort))
            {
                string serviceUrl = Environment.GetEnvironmentVariable("SERVICE_URL");
                if (string.IsNullOrEmpty(serviceUrl))
                {
                    throw new ApplicationException("SERVICE_URL env not found!");
                }
                return new System.ServiceModel.EndpointAddress(serviceUrl);
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.ServiceImpPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.ServiceImpPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceImpPort,
        }
    }
}
